project:
  type: website
  output-dir: docs

website:
  title: "eBird Hotspot Manual"
  navbar: true
  page-footer: 
    left:
      - text: "eBird Hotspot Review Guidelines (v.1.1.0 | Apr 2026)"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home Page

      - href: Introduction.qmd
        text: Introduction

      - href: Part1.qmd
        section: "Part 1: How to Review and Edit Hotspots"
        contents:
          - href: Overview.qmd
            text: Overview
          - href: ToAcceptorNotAccept.qmd
            text: To Accept or Not Accept
          - href: NewHotspotEvaluation.qmd
            text: New Hotspot Evaluation
          - href: ViewingReviewedHotspots.qmd
            text: Viewing Reviewed Hotspots
          - href: EditingExistingHotspots.qmd
            text: Editing Existing Hotspots
          - href: PlottingHotspots.qmd
            text: Plotting Hotspots
          - href: MergingHotspots.qmd
            text: Merging Hotspots

      - href: Part2.qmd
        section: "Part 2: Hotspot Content"
        contents:
          - href: ContentPermissions.qmd
            text: Content Permissions
            contents:
              - href: AssigningContentEditingPermissions.qmd
                text: Assigning Content Editing Permissions         
          - href: HotspotContent.qmd
            text: Hotspot Content
            contents:
              - href: ManagingLanguages.qmd
                text: Managing Languages
              - href: Links.qmd
                text: Links
              - href: ContentEditHistory.qmd
                text: Content Edit History
              - href: Auto-Approval.qmd
                text: Auto-Approval
          - href: Reviewingcontentsuggestions.qmd
            text: Reviewing Content Suggestions
            contents:
              - href: Pendingsuggestions.qmd
                text: Pending Suggestions
              - href: Reviewedsuggestions.qmd
                text: Reviewed Suggestions
          - href: HotspotcontentFAQs.qmd
            text: Hotspot Content FAQs

      - href: Part3.qmd
        section: "Part 3: Hotspot Groups"
        contents: 
          - href: GroupsIntroduction.qmd
            text: Hotspot Groups Overview
          - href: ParentHotspots.qmd
            text: Parent Hotspots
            contents:
              - href: ParentHotspotContent.qmd
                text: Parent Hotspot Content
              - href: AdditionalParentHotspotUI.qmd
                text: Additional Parent Hotspot UI
              - href: DataAggregation.qmd
                text: Data Aggregation
              - href: ParentHotspotPlacement.qmd
                text: Parent Hotspot Placement
              - href: NamingParentandSub-Hotspots.qmd
                text: Naming Parent Hotspots and Sub-hotspots
              - href: List-buildingParentHotspots.qmd
                text: List-building Parent Hotspots
          - href: CreatingandManaging.qmd
            text: Creating and Managing Hotspot Groups
          - href: Multi-RegionHotspotGroups.qmd
            text: Multi-Region Hotspot Groups
          - href: HotspotGroupFAQs.qmd
            text: Hotspot Group FAQs
        
            

      - href: Part4.qmd
        section: "Part 4: Standards and Naming Conventions for eBird Hotspots"
        contents:
          - href: Capitalization.qmd
            text: Capitalization
          - href: Language.qmd
            text: Language
          - href: HotspotDefinitions.qmd
            text: Hotspot Definitions and Hierarchy
          - href: HotspotNaming-Groups.qmd
            text: Hotspot Naming-Groups
          - href: LinearRoutes.qmd
            text: Linear Routes
            contents:
              - href: BirdingTrails.qmd
                text: Birding Trails
          - href: AdditionalModifiers.qmd
            text: Additional Modifiers
            contents:
              - href: Towns.qmd
                text: Towns
              - href: AbbreviationsEnglish.qmd
                text: Abbreviations (English)
              - href: AbbreviationsSpanish.qmd
                text: Abbreviations (Spanish)
              - href: AbbreviationsFrench.qmd
                text: Abbreviations (French)
              - href: OtherAbbreviations.qmd
                text: Other Abbreviations
              - href: RestrictedAccessLocations.qmd
                text: Restricted Access Locations
              - href: HistoricalLocations.qmd
                text: Historical Locations
              - href: StakeoutHotspots.qmd
                text: Stakeout Hotspots
              - href: PelagicHotspots.qmd
                text: Pelagic Hotspots
              - href: PrivacyConcerns.qmd
                text: Privacy Concerns
              - href: BirdcamHotspots.qmd
                text: Birdcam Hotspots
              - href: MiscNaming.qmd
                text: Miscellaneous Hotspot Naming Conventions
          - href: DownloadHotspotFile.qmd
            text: Downloadable Hotspot file through the Hotspot API
            contents:
              - href: ViewInGoogleEarth.qmd
                text: View the Hotspot API file in Google Earth
      - href: Acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme: cosmo
    toc: true
    from: markdown-smart
