### **Abbreviations (English)**

-   Avenue – Ave.

-   Conservation Area – CA

-   County – Co.

-   Department – Dept.

-   Highway – Hwy.

    -   United States Highway 6 – US-6

    -   Colorado Highway 8 – CO-8

    -   Interstate Highway 90 – I-90

    -   County Road 18 – CR-18

-   Important Bird Area – IBA

-   Kilometer – km

-   Mile marks – mm (e.g., I-90--mm92)

-   Mountain or Mount – Mt.

-   National Historic Site – NHS

-   National Park – NP 

-   National Wildlife Refuge – NWR

-   Natural Area – NA

-   National Monument – NM

-   Point – Pt. (do not use this for Port)

-   Road – Rd. 

-   Saint – St

-   State Park – SP

-   Street – St.

-   Township – Twp.

-   Wildlife Area – WA

-   Wildlife Management Area – WMA

-   Wastewater Treatment Plant, Water Treatment Plant, or Sewage Plant – WTP

\*Special note for Wastewater Treatment Plants, which may have different terminology in different regions. Water Treatment Plant, Sewage Ponds, Sewage Lagoons, Sewage Treatment Plant etc. all refer to basically the same type of site (which of course are almost always hot spots for birds!). In the interest of standardization, we recommend using WTP wherever possible. If a certain site is widely known as Sewage Treatment Plant and using WTP would create confusion, it is permissible to spell those out; do not use STP or WWTP.