### **List-building Parent Hotspots (Very Large Areas)**

In Hotspot Groups, the Parent hotspot represents the entire area covered by the group. However, some areas are so large that the Parent hotspot carries too much spatial uncertainty to be useful for scientific analyses. 

For example, Yellowstone National Park covers 13,000 square miles (33,670 square km) and spans four US states. Any checklist assigned to the "Yellowstone National Park (general area)" hotspot lacks the spatial precision needed for eBird Status and Trends models.

Currently, when a traveling checklist covers a distance of 50 mi (80 km) or more, we automatically mark it Not Public. 

**When the area within the bounding box of the group covers 80 km2 or more…**

The Parent hotspot will not appear as a Recommended Location for eBird Mobile checklists and cannot be selected from the map when submitting eBird Mobile checklists (the parent location will still appear on eBird Mobile Explore). 

We recommend marking any checklist submitted to a List-building Parent hotspot ‘Not Public’ with the reason “Checklist-List Building”