### **Pelagic Hotspots**

It is not encouraged to use hotspots for pelagic birding, since the eBird best practice is to follow the [eBird Pelagic Protocol](https://support.ebird.org/en/support/solutions/articles/48000950859-guide-to-ebird-protocols#anchorPelagic) and plot locations based on the exact route you traveled, ideally using tracks in eBird mobile. But there are two scenarios where hotspots have been established and these can be useful for aggregating data, especially when the data were not collected with rigorous tracks of GPS location services.

1.  General pelagic locations: Like other list-building parent hotspots , these are most useful for aggregation of historical data under a single hotspot that is reasonably well sited. They should be named according to conventions described above for list-building parent hotspots and should only be used when established boat trips regularly visit roughly the same waters.

-   Examples:

    -   [Kaikoura--offshore--Albatross Encounter pelagic (general)](https://ebird.org/hotspot/L521309)

    -   [Tofino pelagic trip](https://ebird.org/hotspot/L339307)

2.  Specific pelagic locations: Sometimes an underwater feature (e.g., canyon, seamount, shelf, bank) or other specific habitat is a specific area that is regularly targeted for pelagic birding. These can be appropriate hotspots, but of course should only be used for observations in the immediate vicinity of these features; since this is hard to define for a birder on a boat, these hotspots should only be established with good reason and should always be used with great care. Otherwise, see above for conventions.

-   Examples:

    -   [Hudson Canyon (Atlantic Ocean)](https://ebird.org/hotspot/L670979)

    -   [Escollo Gorda](https://ebird.org/hotspot/L504177)